version: "3"
networks:
    gmiak:

services:
    server:
        image: gmiak/bthloggen-server:1.0
        container_name: "bthloggen-server"
        ports:
            - "1338:1337"
        volumes:
            - "./data/:/data/"
        networks:
            gmiak:
        restart:
            "always"
    client:
        image: gmiak/bthloggen-client:1.0
        container_name: "bthloggen-client"
        networks:
            gmiak:
        links:
            - server:myserver
  
